f2b

diff --git a/install_scripts/locenv b/install_scripts/locenv
--- a/install_scripts/locenv
+++ b/install_scripts/locenv
@@ -6,7 +6,21 @@ log() {
     disp "`date -Iseconds`" "$@"
 }
 
+err() {
+    disp "`date -Iseconds`" "ERROR:" "$@"
+}
+
+fat() {
+    disp "`date -Iseconds`" "ERROR:" "$@"
+    exit 1
+}
+
 cmd() {
     log running "$@"
     "$@"
+    st=$?
+    if [ $st -ne 0 ] ; then
+      err "running" "$@" "failed"
+    fi
+    return $st
 }
